name: testing the github actions

on:
  pull_request:
    types: [opened]

jobs:
  
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: install dependencies
        run: npm ci
  